"""
Django settings for contact_backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = "C:\\Users\\Squar\\Documents\\GitHub\\Squarerootof6.github.io\\"
DEBUG = True
SECRET_KEY = "django-insecure-1234567890abcdefghijklmn"
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 必需的中间件
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # 必需的中间件
    'django.contrib.messages.middleware.MessageMiddleware',  # 必需的中间件
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
STATIC_URL = './'  # 设置静态文件的 URL 路径

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR],  # 指向 assets 目录
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
ALLOWED_HOSTS = ['*']
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets\\'),
]
ROOT_URLCONF = 'contact_backend.urls'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',  # 确保这一行存在
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contact_form',  # 你的应用
]